[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sparse_wf"
version = "0.0.1"
readme = "README.md"
dependencies = [
    "jax>=0.4.20",
    "jaxlib",
    "flax",
    "optax",
    "chex",
    "tqdm",
    "einops",
    "numpy",
    "matplotlib",
    "folx",
    "pyscf",
]

[project.optional-dependencies]
dev = ["ruff", "pre-commit"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# jaxtyping violates F722: https://docs.kidger.site/jaxtyping/faq/#flake8-or-ruff-are-throwing-an-error
ignore = ["F722"]

[tool.mypy]
strict = false
exclude = [
    "sparse_wf/preliminary_experiments"
    ]
disable_error_code = ["valid-type", "import-untyped", "import-not-found"]
