batch_size: 5
init_width: 0.1
logging_args:
  collection: ''
  comment: ''
  file:
    file_name: log.txt
    use: true
  name_keys: []
  out_directory: .
  smoothing: 500
  wandb:
    entity: tum_daml_nicholas
    project: debug
    use: false
mcmc_steps: 20
metadata:
  commit: ''
  cwd: ''
  experiment_name: debug
model: moon2step
model_args:
  cutoff: 10.0
  feature_dim: 256
  nuc_mlp_depth: 3
  pair_mlp_widths: [16, 8]
  pair_n_envelopes: 32
  n_determinants: 4
  n_envelopes: 8
  use_e_e_cusp: True
  mlp_jastrow:
    use: false
    embedding_n_hidden: [40,40]
    soe_n_hidden:
molecule_args:
  args:
    atom: Li 0 0 0; H 3 0 0
    spin: 0
  basis: sto-6g
  method: from_str
optimization:
  burn_in: 0
  clipping:
    clip_local_energy: 5.0
    stat: median
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        decay: 1.0
        delay: 1000
        init_value: 0.1
    transformations:
    - args: []
      kwargs:
        max_norm: 1.0
      name: clip_by_global_norm
  preconditioner_args:
    cg_args:
      damping: 0.001
      maxiter: 100
    preconditioner: svd
    spring_args:
      damping: 0.001
      decay_factor: 0.99
    svd_args:
      damping: 0.001
      ema_S: 0.9
      ema_natgrad: 0.9
      history_length: 200
  steps: 50000
pretraining:
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        decay: 1.0
        delay: 1000
        init_value: 0.001
    transformations:
    - args: []
      kwargs:
        max_norm: 1.0
      name: clip_by_global_norm
    - args: []
      kwargs: {}
      name: scale_by_adam
    - args: []
      kwargs: {}
      name: scale_by_trust_ratio
  steps: 0
seed: 64204
