molecule: "Be 0 0 0"
spin: 0

model_args:
  cutoff: 10.0

pretraining:
  steps: 0

optimization:
  burn_in: 0
  steps: 50_000
  preconditioner_args:
    preconditioner: cg

logging_args:
  wandb:
    use: False
    entity: tum_daml_nicholas
    project: debug

batch_size: 2048
