molecule: "Be 0 0 0"
spin: 0

model_args:
  cutoff: 20.0

pretraining:
  steps: 0

optimization:
  burn_in: 0
  steps: 50_000
  preconditioner_args:
    preconditioner: svd
    svd_args:
      damping: 1.0e-3
      ema_natgrad: 0.9
      ema_S: 0.9
      history_length: 200


logging_args:
  wandb:
    use: False
    entity: tum_daml_nicholas
    project: svd_preconditioner

batch_size: 5
