molecule: "Be 0 0 0"
spin: 0

model_args:
  cutoff: 10.0


optimization:
  # learning_rate: 0.001
  # grad_norm_constraint: 0.1
  preconditioner_args:
    preconditioner: spring
    spring_args:
      damping: 5.e-3

logging_args:
  smoothing: 500
  file:
    use: True
    path: "log.txt"
  wandb:
    use: True
    entity: leongerard
    project: debug

batch_size: 512
pretrain_steps: 700
