batch_size: 2048
init_width: 0.1
logging_args:
  collection: ''
  comment: ''
  file:
    file_name: log.txt
    use: true
  name_keys: []
  out_directory: .
  smoothing: 5000
  wandb:
    entity: tum_daml_nicholas
    project: accuracy
    use: true
metadata:
  commit: ''
  cwd: ''
  experiment_name: H-chain_sparse_newStatic
model: moon
model_args:
  embedding:
    cutoff: 3.0
    feature_dim: 256
    nuc_mlp_depth: 4
    pair_mlp_widths:
    - 16
    - 8
    pair_n_envelopes: 32
  jastrow:
    e_e_cusps: psiformer
    mlp_depth: 2
    mlp_width: 64
    use_log_jastrow: true
    use_mlp_jastrow: true
  n_determinants: 16
  n_envelopes: 8
molecule_args:
  basis: sto-6g
  chain_args:
    distance: 1.8
    element: '1'
    n: 20
  database_args:
    comment: ''
    hash: ''
    name: ''
  from_str_args:
    atom: ''
    spin: 0
  method: chain
optimization:
  burn_in: 50
  clipping:
    clip_local_energy: 5.0
    stat: median
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        decay: 1.0
        delay: 1000
        init_value: 0.1
    transformations:
    - args: []
      kwargs:
        max_norm: 1.0
      name: clip_by_global_norm
  preconditioner_args:
    cg_args:
      damping: 0.001
      maxiter: 100
    preconditioner: spring
    spring_args:
      damping: 0.001
      decay_factor: 0.99
    svd_args:
      damping: 0.001
      ema_S: 0.9
      ema_natgrad: 0.9
      history_length: 200
  steps: 100000
pretraining:
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        decay: 1.0
        delay: 1000
        init_value: 0.001
    transformations:
    - args: []
      kwargs:
        max_norm: 1.0
      name: clip_by_global_norm
    - args: []
      kwargs: {}
      name: scale_by_adam
    - args: []
      kwargs: {}
      name: scale_by_trust_ratio
  steps: 10
seed: 390
