molecule: "Be 0 0 0"
spin: 0

model_args:
  cutoff: 3.0

optimization:
  preconditioner_args:
    preconditioner: cg

logging_args:
  wandb:
    entity: tum_daml_nicholas
    project: compare_energies

pretrain_steps: 200