molecule: "Be 0 0 0"
spin: 0

model_args:
  cutoff: 10.0
  feature_dim: 256
  nuc_mlp_depth: 3
  pair_mlp_widths: [16, 8]
  pair_n_envelopes: 32
  n_determinants: 4

logging_args:
  smoothing: 500
  wandb:
    use: true
    project: sparse_wf
    entity: tum_daml_nicholas
  file:
    use: false
    path: "log.txt"

optimization:
  steps: 100_000
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        init_value: 0.1
        decay: 1.0
        delay: 1000
    transformations:
      - name: clip_by_global_norm
        args: []
        kwargs: { max_norm: 1.0 }
  preconditioner_args:
    preconditioner: spring
    spring_args:
      damping: 1.e-3
      decay_factor: 0.99
    cg_args:
      damping: 1.e-3
      maxiter: 100
  clipping:
    clip_local_energy: 5.0
    stat: median

pretraining:
  steps: 1_000
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        init_value: 0.001
        decay: 1.0
        delay: 1000
    transformations:
      - name: clip_by_global_norm
        args: []
        kwargs: { max_norm: 1.0 }
      - name: scale_by_adam
        args: []
        kwargs: {}
      - name: scale_by_trust_ratio
        args: []
        kwargs: {}

batch_size: 512
mcmc_steps: 20
init_width: 0.1
basis: sto-6g
