metadata:
  experiment_name: ""
  commit: ""
  cwd: ""

seed: 0

molecule_args:
  method: from_str
  database_args:
    hash: ""
    name: ""
    comment: ""
  from_str_args:
    atom: "Li 0 0 0; H 3 0 0"
    spin: 0
  chain_args:
    element: "H"
    distance: 2.0
    n: 10
  basis: sto-6g

model: moon

model_args:
  n_determinants: 16
  embedding:
    embedding: new
    new:
      cutoff: 5.0
      cutoff_1el: 20.0
      feature_dim: 256
      pair_mlp_widths: [16, 8]
      pair_n_envelopes: 32
      low_rank_buffer: 2
      n_updates: 1
    moon:
      cutoff: 5.0
      cutoff_1el: 20.0
      feature_dim: 256
      nuc_mlp_depth: 4
      pair_mlp_widths: [16, 8]
      pair_n_envelopes: 32
      low_rank_buffer: 2
  jastrow:
    e_e_cusps: psiformer
    use_log_jastrow: True
    use_mlp_jastrow: True
    mlp_depth: 2
    mlp_width: 64
  envelopes:
    envelope: isotropic
    isotropic_args:
      n_envelopes: 8
    glu_args:
      n_envelopes: 8
      width: 32
      depth: 2

logging_args:
  smoothing: 5000
  checkpoint_every: 10_000
  wandb:
    use: true
    entity: tum_daml_nicholas
    project: default
  file:
    use: true
    file_name: log.txt
  python:
    use: true
  name_keys: []
  out_directory: "."
  collection: ""
  comment: ""

optimization:
  energy_operator: sparse
  steps: 100_000
  burn_in: 500
  max_batch_size: 16
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        init_value: 0.1
        decay: 1.0
        delay: 1000
    transformations:
      - name: clip_by_global_norm
        args: []
        kwargs: { max_norm: 1.0 }
  preconditioner_args:
    preconditioner: spring
    spring_args:
      damping: 1.e-3
      decay_factor: 0.99
    spring_dense_args:
      damping: 1.e-3
      decay_factor: 0.99
      max_batch_size: 128
      use_float64: true
    cg_args:
      damping: 1.e-3
      maxiter: 100
    svd_args:
      damping: 1.e-3
      ema_natgrad: 0.9
      ema_S: 0.9
      history_length: 200
  clipping:
    clip_local_energy: 5.0
    stat: median
  spin_operator_args:
    operator: none
    grad_scale: 1.e-4

pretraining:
  steps: 1_000
  sample_from: wf
  optimizer_args:
    lr_schedule: hyperbolic
    lr_schedule_args:
      hyperbolic:
        init_value: 0.001
        decay: 1.0
        delay: 1000
    transformations:
      - name: clip_by_global_norm
        args: []
        kwargs: { max_norm: 1.0 }
      - name: scale_by_adam
        args: []
        kwargs: {}
      - name: scale_by_trust_ratio
        args: []
        kwargs: {}

load_checkpoint: ""

evaluation:
  steps: 0
  compute_energy: True

batch_size: 512

mcmc_args:
  proposal: "all-electron"
  all_electron_args:
    steps: 20
    init_width: 0.1
  single_electron_args:
    sweeps: 1
    init_width: 0.5
  cluster_update_args:
    sweeps: 1
    init_width: 0.2
    max_cluster_radius: 2.0
    max_cluster_size: 5
