seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-dgx-a100-40x8
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-hgx-a100-80x4

fixed:
  logging_args.wandb.project: ngao_cumulene_pp
  molecule_args.method: database
  logging_args.name_keys:
    - molecule_args.database_args.name
    - molecule_args.pseudopotentials
    - model_args.jastrow.use_mlp_jastrow
  model_args.embedding.new.cutoff: 3.0

grid:
  molecule_args:
    database_args:
      name:
        type: choice
        options:
          - cumulene_C16H4_0deg_singlet
          - cumulene_C16H4_90deg_triplet

# default:
#   fixed:
#     molecule_args.pseudopotentials: []

pp:
  fixed:
    molecule_args.pseudopotentials: ["C"]
# jastrow:
#   fixed:
#     model_args.jastrow.use_mlp_jastrow: True
#     model_args.jastrow.use_log_jastrow: True
