seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-dgx-a100-40x8
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-hgx-a100-80x4

fixed:
  logging_args.wandb.project: ngao_cumulene_jastrow
  molecule_args.method: database
  model_args:
    spin_restricted: True
    embedding:
      embedding: new
      new.cutoff: 3.0
  pretraining.reference: hf

grid:
  molecule_args:
    database_args:
      spin:
        type: choice
        options:
          - 0
          - 2
      name:
        type: choice
        options:
          - cumulene_C4H4_0deg
          - cumulene_C4H4_90deg
          - cumulene_C8H4_0deg
          - cumulene_C8H4_90deg
          - cumulene_C16H4_0deg
          - cumulene_C16H4_90deg
          # - cumulene_C20H4_0deg
          # - cumulene_C20H4_90deg
          # - cumulene_C30H4_0deg
          # - cumulene_C30H4_90deg
          # - cumulene_C40H4_0deg
          # - cumulene_C40H4_90deg
