seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-dgx-a100-40x8
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 16
      mem: 64G
      partition: mcml-hgx-a100-80x4

fixed:
  model_args.embedding:
    embedding: new
    new.cutoff: 3.0

grid:
  molecule_args:
    database_args:
      name:
        type: choice
        options:
          # - cumulene_C4H4_0deg
          # - cumulene_C4H4_90deg
          - cumulene_C6H4_0deg
          - cumulene_C6H4_90deg
          # - cumulene_C10H4_0deg
          # - cumulene_C10H4_90deg
          # - cumulene_C20H4_0deg
          # - cumulene_C20H4_90deg
          # - cumulene_C30H4_0deg
          # - cumulene_C30H4_90deg
          # - cumulene_C40H4_0deg
          # - cumulene_C40H4_90deg

no_jastrow:
  fixed:
    model_args.jastrow.use_attention: False

attention:
  fixed:
    model_args.jastrow.use_attention: True

pair:
  fixed:
    model_args.jastrow.use_e_e_mlp: True

both:
  fixed:
    model_args.jastrow.use_attention: True
    model_args.jastrow.use_e_e_mlp: True
