seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0
    mem: 4G
    cpus-per-task: 1
    time: 0-00:20
    partition: cpu,cpu_large
    qos: phdcpu
    nodes: 1
    tasks-per-node: 2

fixed:
  logging_args:
    out_directory: logs
  batch_size: 16
  pretrain_steps: 10
  optimization.steps: 10
  logging_args.name_keys:
    - optimization.preconditioner_args.preconditioner

grid:
  optimization.preconditioner_args.preconditioner:
    type: choice
    options: [spring, cg]
