seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:2
      cpus-per-task: 16
      partition: gpu_h100
      mem: 64G

fixed:
  molecule_args:
    method: chain
    chain_args:
      element: H
      distance: 1.8
      n: 30
  batch_size: 2048
  optimization:
    steps: 20_000
    # energy_operator: dense
    energy_operator: sparse
  mcmc_args:
    # proposal: all-electron
    proposal: single-electron

grid:
  model_args.embedding.n_updates:
    type: choice
    options: [2, 4]
  model_args.embedding.cutoff:
    type: choice
    options: [5.0, 9.0]

none:
  fixed:
    optimization.spin_operator_args.operator: none
# splus:
#   fixed:
#     optimization.spin_operator_args.operator: splus
#   grid:
#     optimization.spin_operator_args.grad_scale:
#       type: choice
#       options: [1.e-3]

# cutoff:
#   fixed:
#     optimization.spin_operator_args.operator: none
#     model_args:
#       embedding:
#         cutoff: 5.0
