seml:
  executable: train.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem: 100G
    cpus-per-task: 8
    time: 10-00:00
    partition: hgx
    qos: normal
    nodes: 1
    tasks-per-node: 1

fixed:
  molecule_args:
    method: from_str
    args:
      atom: "N 0 0 0; N 2.068 0 0"
  batch_size: 2048
  pretraining:
    steps: 500
  optimization:
    steps: 10_000
    preconditioner_args:
      preconditioner: cg

  logging_args.name_keys:
    - model

grid:
  model:
    type: choice
    options: [moon]
