seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:1
      cpus-per-task: 8
      mem: 64G
      partition: gpu_a100

fixed:
  molecule_args.method: from_str

grid:
  molecule_args.from_str_args.atom:
    type: choice
    options:
      - N 0 0 0; N 2.068 0 0
      - N 0 0 0; N 3.0 0 0
      - N 0 0 0; N 4.0 0 0
      - N 0 0 0; N 5.0 0 0
