seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:1
      cpus-per-task: 4
      mem: 32G
      partition: gpu_h100

fixed:
  +conf: config/n2.yaml

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
