seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:2
      cpus-per-task: 16
      mem: 64G
      partition: mcml-dgx-a100-40x8
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:2
      cpus-per-task: 16
      mem: 64G
      partition: mcml-hgx-a100-80x4

fixed:
  logging_args.wandb.project: ngao_n2
  # pretraining.steps: 10_000
  pretraining.steps: 0
  mcmc_args.proposal: all-electron
  optimization.energy_operator: dense
  optimization.preconditioner_args.preconditioner: spring_dense

  logging_args.name_keys:
    - model_args.embedding.new.cutoff
    - molecule_args.from_str_args.atom

  molecule_args.method: from_str
  model_args.embedding.embedding: new
  batch_size: 4096
  logging_args.python.use: False

grid:
  molecule_args.from_str_args.atom:
    type: choice
    options:
      # - "N 0 0 0; N 2.068 0 0"
      # - "N 0 0 0; N 3.0 0 0"
      # - "N 0 0 0; N 4.0 0 0"
      # - "N 0 0 0; N 5.0 0 0"
      - "N 0 0 0; N 6.0 0 0"
  model_args.embedding.new.cutoff:
    type: choice
    options:
      - 1
      - 3
      - 6
      - 9
