seml:
  executable: train_with_seml.py
  project_root_dir: ../../
  output_dir: ~/slurm-output/

slurm:
  # - experiments_per_job: 1
  #   sbatch_options:
  #     gres: gpu:4
  #     cpus-per-task: 16
  #     mem: 64G
  #     partition: gpu_h100
  # - experiments_per_job: 1
  #   sbatch_options:
  #     gres: gpu:8
  #     cpus-per-task: 16
  #     mem: 64G
  #     partition: gpu_a100
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:8
      cpus-per-task: 32
      mem: 256G
      partition: mcml-dgx-a100-40x8
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:4
      cpus-per-task: 32
      mem: 256G
      partition: mcml-hgx-h100-92x4

fixed:
  logging_args.wandb.project: ngao_zhai
  logging_args.name_keys:
    - molecule_args.database_args.name
  molecule_args.method: database
  molecule_args.pseudopotentials: [C, S, Fe]
  optimization.pp_grid_points: 6

grid:
  molecule_args.database_args.name:
    type: choice
    options:
      - zhai_et_al_2023_HFe_df2-tzvp
      - zhai_et_al_2023_HC_df2-tzvp
      - zhai_et_al_2023_HFe2_df2-tzvp
      - zhai_et_al_2023_HS_df2-tzvp
      # - zhai_et_al_2023_HFe_df2-svp
      # - zhai_et_al_2023_HC_df2-svp
      # - zhai_et_al_2023_HFe2_df2-svp
      # - zhai_et_al_2023_HS_df2-svp
