name: Test main branch

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev version of folx and seml
        run: |
          git clone https://github.com/microsoft/folx.git ../folx
          git clone https://github.com/TUM-DAML/seml.git ../seml
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.18"
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Test with pytest
        run: JAX_PLATFORM_NAME=cpu uv run pytest
