name: Test main branch

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system pytest
          uv pip install --system .
      - name: Setup dev version of folx
        run: |
          git clone https://github.com/microsoft/folx.git folx
          uv pip install --system folx/
      - name: Test with pytest
        run: |
          pytest
