name: Test main branch

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev version of folx and seml
        run: |
          git clone https://github.com/microsoft/folx.git ../folx
          git clone https://github.com/TUM-DAML/seml.git ../seml
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh
      - name: Install dependencies
        run: uv sync
      - name: Remove cuda
        run: uv remove jax; uv add jax
      - name: Test with pytest
        run: JAX_PLATFORM_NAME=cpu uv run pytest
